/* eslint-disable */
// Snapshot generated by Expo Router 57 from this fixture's app directory.
// Regenerate with `pnpm exec expo start`, then copy `.expo/types/router.d.ts` here.
import * as Router from 'expo-router'

export * from 'expo-router'

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams:
        | { pathname: Router.RelativePathString; params?: Router.UnknownInputParams }
        | { pathname: Router.ExternalPathString; params?: Router.UnknownInputParams }
        | { pathname: `/details`; params?: Router.UnknownInputParams }
        | { pathname: `/`; params?: Router.UnknownInputParams }
        | { pathname: `/_sitemap`; params?: Router.UnknownInputParams }
        | {
            pathname: `/posts/[postId]`
            params: Router.UnknownInputParams & { postId: string | number }
          }
      hrefOutputParams:
        | { pathname: Router.RelativePathString; params?: Router.UnknownOutputParams }
        | { pathname: Router.ExternalPathString; params?: Router.UnknownOutputParams }
        | { pathname: `/details`; params?: Router.UnknownOutputParams }
        | { pathname: `/`; params?: Router.UnknownOutputParams }
        | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams }
        | {
            pathname: `/posts/[postId]`
            params: Router.UnknownOutputParams & { postId: string }
          }
      href:
        | Router.RelativePathString
        | Router.ExternalPathString
        | `/details${`?${string}` | `#${string}` | ''}`
        | `/${`?${string}` | `#${string}` | ''}`
        | `/_sitemap${`?${string}` | `#${string}` | ''}`
        | { pathname: Router.RelativePathString; params?: Router.UnknownInputParams }
        | { pathname: Router.ExternalPathString; params?: Router.UnknownInputParams }
        | { pathname: `/details`; params?: Router.UnknownInputParams }
        | { pathname: `/`; params?: Router.UnknownInputParams }
        | { pathname: `/_sitemap`; params?: Router.UnknownInputParams }
        | `/posts/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}`
        | {
            pathname: `/posts/[postId]`
            params: Router.UnknownInputParams & { postId: string | number }
          }
    }
  }
}
