#!/usr/bin/env bash
set -euo pipefail

package=dev.hozo.threenativeprobe
root="$(cd "$(dirname "$0")/.." && pwd)"
artifacts="${1:-$root/artifacts}"
speech_apk="$root/../native-demo/speech-log/build/outputs/apk/debug/speech-log-debug.apk"
engine=dev.hozo.speechlog
talkback=com.google.android.marvin.talkback
talkback_service="$talkback/com.google.android.marvin.talkback.TalkBackService"

spoken() {
  adb logcat -d -v raw -s HozoSpeech:I | tr -d '\r' | grep -v '^--------- ' || true
}

settle() {
  local last now quiet=0
  last="$(spoken | wc -l)"
  for _ in $(seq 1 20); do
    sleep 1
    now="$(spoken | wc -l)"
    if [ "$now" = "$last" ]; then
      quiet=$((quiet + 1))
      [ "$quiet" -lt 3 ] || return 0
    else
      quiet=0
      last=$now
    fi
  done
}

[ -f "$speech_apk" ] || speech_apk="$(
  find "$root/../native-demo/speech-log/build/outputs/apk/debug" -name '*.apk' -print -quit
)"
test -f "$speech_apk"
test -n "$(adb shell pidof "$package" | tr -d '\r')"
adb install -r "$speech_apk"
adb shell settings put secure tts_default_synth "$engine"
adb shell pm grant "$talkback" android.permission.POST_NOTIFICATIONS 2>/dev/null || true
adb logcat -c
adb shell settings put secure enabled_accessibility_services "$talkback_service"
adb shell settings put secure accessibility_enabled 1

for _ in $(seq 1 30); do
  # Do not use grep -q in this pipe: under pipefail, its early exit can give
  # dumpsys SIGPIPE (141) after TalkBack was found successfully.
  if adb shell dumpsys accessibility | tr -d '\r' | grep 'TalkBackService' >/dev/null; then break; fi
  sleep 1
done
adb shell dumpsys accessibility | tr -d '\r' | grep 'TalkBackService' >/dev/null

for _ in $(seq 1 20); do
  [ -z "$(spoken)" ] || break
  sleep 1
done
settle

# Hardware Tab is the supported deterministic driver on this image. The
# labelled image is explicitly focusable, while fallback exposes its own
# button. The decorative subtree must remain absent from every utterance.
for _ in $(seq 1 12); do
  adb shell input keyevent KEYCODE_TAB
  settle
done

spoken > "$artifacts/talkback-final.txt"
grep -q 'Labelled GPU cube' "$artifacts/talkback-final.txt"
grep -q 'Inspect fallback cube data' "$artifacts/talkback-final.txt"
if grep -q 'Decorative GPU cube sentinel' "$artifacts/talkback-final.txt"; then
  echo 'decorative GPU content was announced by TalkBack' >&2
  exit 1
fi

# Start a fresh surface and traverse controls generated by the public
# r3f-native wrapper. This second run stays mounted; the measured first run
# above already proved renderer teardown.
adb logcat -c
adb shell am force-stop "$package" || true
adb shell am start -W -n "$package/.MainActivity"
for _ in $(seq 1 45); do
  adb logcat -d -v brief | grep -q '\[hozo-three-native\].*"event":"first_frame"' && break
  sleep 1
done
adb logcat -d -v brief | grep -q '\[hozo-three-native\].*"event":"first_frame"'
for _ in $(seq 1 12); do
  adb shell input keyevent KEYCODE_TAB
  settle
done
spoken > "$artifacts/talkback-public-controls.txt"
grep -q 'Activate measured cube' "$artifacts/talkback-public-controls.txt"
grep -q 'Open measured cube details' "$artifacts/talkback-public-controls.txt"
grep -qi 'button' "$artifacts/talkback-public-controls.txt"
grep -qi 'link' "$artifacts/talkback-public-controls.txt"

cat "$artifacts/talkback-final.txt" "$artifacts/talkback-public-controls.txt" > "$artifacts/talkback.txt"
adb exec-out screencap -p > "$artifacts/talkback.png" 2>/dev/null || true
