// Generated by scripts/view-base.mjs from the Web backend's shared CSS.
export const HOZO_VIEW_BASE_CSS = `@layer base {
  :where(.hozo-view) {
    display: flex;
    flex-direction: column;
    flex-shrink: 0;
    position: relative;
    min-width: 0;
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    border: 0 solid;
  }
}
`
