// Native half of the zero-setup facade. Ownership is identical to the Web
// entry; package export conditions select each owner's native implementation.

// The connection to a project's i18n library (decision 008). Behaviors owns
// it because every component that shows a string already depends on it.
export {
  fromI18next,
  fromReactIntl,
  type HozoI18n,
  HozoI18nProvider,
  type HozoI18nProviderProps,
  type HozoMessageKey,
  type HozoMessageParams,
  hozoMessages,
  type I18nextLike,
  type ReactIntlLike,
  useHozoI18n,
} from '@hozo/behaviors'
export type { Autocomplete } from '@hozo/patterns'
export {
  avatarInitials,
  Dialog,
  type DialogProps,
  HozoAvatar as Avatar,
  HozoAvatar,
  type HozoAvatarProps as AvatarProps,
  type HozoAvatarProps,
  type HozoAvatarStatus as AvatarStatus,
  type HozoAvatarStatus,
  HozoChip as Chip,
  HozoChip,
  type HozoChipProps as ChipProps,
  type HozoChipProps,
  HozoCombobox as Combobox,
  HozoCombobox,
  type HozoComboboxOption as ComboboxOption,
  type HozoComboboxOption,
  type HozoComboboxProps as ComboboxProps,
  type HozoComboboxProps,
  HozoListbox as Listbox,
  HozoListbox,
  type HozoListboxOption as ListboxOption,
  type HozoListboxOption,
  type HozoListboxProps as ListboxProps,
  type HozoListboxProps,
  HozoMenu as Menu,
  HozoMenu,
  type HozoMenuItem as MenuItem,
  type HozoMenuItem,
  type HozoMenuProps as MenuProps,
  type HozoMenuProps,
  HozoOtpInput as OtpInput,
  HozoOtpInput,
  type HozoOtpInputProps as OtpInputProps,
  type HozoOtpInputProps,
  HozoPagination as Pagination,
  HozoPagination,
  type HozoPaginationProps as PaginationProps,
  type HozoPaginationProps,
  HozoRadioGroup as RadioGroup,
  HozoRadioGroup,
  type HozoRadioGroupProps as RadioGroupProps,
  type HozoRadioGroupProps,
  type HozoRadioOption as RadioOption,
  type HozoRadioOption,
  type HozoStep as Step,
  type HozoStep,
  HozoStepper as Stepper,
  HozoStepper,
  type HozoStepperProps as StepperProps,
  type HozoStepperProps,
  type HozoStepStatus as StepStatus,
  type HozoStepStatus,
  type HozoTab as Tab,
  type HozoTab,
  HozoTabs as Tabs,
  HozoTabs,
  type HozoTabsProps as TabsProps,
  type HozoTabsProps,
  HozoToolbar as Toolbar,
  HozoToolbar,
  type HozoToolbarItem as ToolbarItem,
  type HozoToolbarItem,
  type HozoToolbarItemProps as ToolbarItemProps,
  type HozoToolbarItemProps,
  type HozoToolbarProps as ToolbarProps,
  type HozoToolbarProps,
  HozoTree as Tree,
  HozoTree,
  type HozoTreeProps as TreeProps,
  type HozoTreeProps,
  type OtpType,
  type TreeNode,
} from '@hozo/patterns'
export * from '@hozo/primitives'
// Resolve the primitives/typography overlap at the facade boundary. Besides
// making ownership explicit, this keeps a Text-only consumer out of the
// typography module on bundlers that follow star re-exports conservatively.
export { Link, type LinkProps, Text, type TextProps } from '@hozo/primitives'
export * from '@hozo/semantics'
export * from '@hozo/typography'
