// Zero-setup facade. Components are implemented by their domain package;
// core deliberately owns no second copy of them.

// The connection to a project's i18n library (decision 008). Behaviors owns
// it because every component that shows a string already depends on it.
export {
  fromI18next,
  fromReactIntl,
  type HozoI18n,
  HozoI18nProvider,
  type HozoI18nProviderProps,
  type HozoMessageKey,
  type HozoMessageParams,
  hozoMessages,
  type I18nextLike,
  type ReactIntlLike,
  useHozoI18n,
} from '@hozo/behaviors'
export {
  type Autocomplete,
  avatarInitials,
  Dialog,
  type DialogProps,
  HozoAvatar as Avatar,
  HozoAvatar,
  type HozoAvatarProps as AvatarProps,
  type HozoAvatarProps,
  type HozoAvatarStatus as AvatarStatus,
  type HozoAvatarStatus,
  HozoChip as Chip,
  HozoChip,
  type HozoChipProps as ChipProps,
  type HozoChipProps,
  HozoCombobox as Combobox,
  HozoCombobox,
  type HozoComboboxOption as ComboboxOption,
  type HozoComboboxOption,
  type HozoComboboxProps as ComboboxProps,
  type HozoComboboxProps,
  HozoListbox as Listbox,
  HozoListbox,
  type HozoListboxOption as ListboxOption,
  type HozoListboxOption,
  type HozoListboxProps as ListboxProps,
  type HozoListboxProps,
  HozoMenu as Menu,
  HozoMenu,
  type HozoMenuItem as MenuItem,
  type HozoMenuItem,
  type HozoMenuProps as MenuProps,
  type HozoMenuProps,
  HozoPagination as Pagination,
  HozoPagination,
  type HozoPaginationProps as PaginationProps,
  type HozoPaginationProps,
  HozoRadioGroup as RadioGroup,
  HozoRadioGroup,
  type HozoRadioGroupProps as RadioGroupProps,
  type HozoRadioGroupProps,
  type HozoRadioOption as RadioOption,
  type HozoRadioOption,
  type HozoTab as Tab,
  type HozoTab,
  HozoTabs as Tabs,
  HozoTabs,
  type HozoTabsProps as TabsProps,
  type HozoTabsProps,
  HozoToolbar as Toolbar,
  HozoToolbar,
  type HozoToolbarItem as ToolbarItem,
  type HozoToolbarItem,
  type HozoToolbarItemProps as ToolbarItemProps,
  type HozoToolbarItemProps,
  type HozoToolbarProps as ToolbarProps,
  type HozoToolbarProps,
  HozoTree as Tree,
  HozoTree,
  type HozoTreeProps as TreeProps,
  type HozoTreeProps,
  type TreeNode,
} from '@hozo/patterns'
export * from '@hozo/primitives'
// These names are also re-exported by typography for convenience. Keep the
// facade's canonical binding explicit so bundlers do not enter typography --
// and retain Ruby's compound-component setup -- for a plain Text or Link.
export { Link, type LinkProps, Text, type TextProps } from '@hozo/primitives'
export * from '@hozo/semantics'
export * from '@hozo/typography'
