import assert from 'node:assert/strict'
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import test from 'node:test'

import { createCompiler } from '@hozo/compiler'
import { CACHE_DIR, StylexModuleCache, type StylexResolvedBindings } from '@hozo/compiler/project'

import { metroStatePath, withHozo } from './config.ts'
import { withWebFontFaces } from './index.ts'
import { transformHozoSource } from './transform.ts'

test('withHozo preserves Metro settings and records the existing transformer', async () => {
  const root = mkdtempSync(path.join(tmpdir(), 'hozo-metro-config-'))
  try {
    mkdirSync(path.join(root, 'src'))
    writeFileSync(
      path.join(root, 'src', 'App.tsx'),
      `import { View } from '@hozo/core'\nexport const App = () => <View className="p-4" />\n`,
    )
    const upstream = path.join(root, 'custom-transformer.cjs')
    const config = {
      projectRoot: root,
      resolver: { sourceExts: ['js', 'tsx'] },
      transformer: { babelTransformerPath: upstream, minifierPath: 'keep-me' },
    }

    const result = await withHozo(config)

    assert.notEqual(result, config)
    assert.deepEqual(result.resolver.sourceExts, config.resolver.sourceExts)
    assert.equal(typeof result.resolver.resolveRequest, 'function')
    assert.equal(result.transformer.minifierPath, 'keep-me')
    assert.match(
      result.transformer.babelTransformerPath,
      /packages[\\/]metro[\\/]src[\\/]index\.ts$/,
    )
    assert.deepEqual(JSON.parse(readFileSync(metroStatePath(root), 'utf8')), {
      upstreamTransformer: upstream,
      // Resolved here and not in the worker: this project's `p-4` is what
      // makes `'auto'` true, and only the config layer scans (#315).
      preflight: true,
    })
    assert.match(
      readFileSync(path.join(root, 'node_modules', '.hozo', 'candidates.native.js'), 'utf8'),
      /Generated by Hozo/,
    )
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})

test('withHozo carries platform-scoped Metro aliases into StyleX lowering', async () => {
  const root = mkdtempSync(path.join(tmpdir(), 'hozo-metro-stylex-alias-'))
  try {
    const src = path.join(root, 'src')
    mkdirSync(src)
    const androidStyles = path.join(src, 'styles.android.ts')
    const iosStyles = path.join(src, 'styles.ios.ts')
    const barrel = path.join(src, 'index.ts')
    const app = path.join(src, 'App.tsx')
    writeFileSync(
      androidStyles,
      `import * as stylex from '@stylexjs/stylex'\n` +
        `export const styles = stylex.create({ root: { marginTop: 37 } })\n`,
    )
    writeFileSync(
      iosStyles,
      `import * as stylex from '@stylexjs/stylex'\n` +
        `export const styles = stylex.create({ root: { marginTop: 41 } })\n`,
    )
    writeFileSync(barrel, `export { styles as cardStyles } from '@theme/styles'\n`)
    const appSource =
      `import * as stylex from '@stylexjs/stylex'\n` +
      `import { View } from '@hozo/core'\n` +
      `import { cardStyles } from '@theme'\n` +
      `export const App = () => <View {...stylex.props(cardStyles.root)} />\n`
    writeFileSync(app, appSource)

    const config = {
      projectRoot: root,
      resolver: {
        marker: 'preserved',
        // Metro hands its resolver a context object it also expects back;
        // the fields this test touches are the two below.
        resolveRequest(
          context: { originModulePath: string; [key: string]: unknown },
          moduleName: string,
          platform: string | null,
        ) {
          if (moduleName === '@theme/styles') {
            return {
              type: 'sourceFile',
              filePath: platform === 'ios' ? iosStyles : androidStyles,
            }
          }
          if (moduleName === '@theme') return { type: 'sourceFile', filePath: barrel }
          return context.resolveRequest(context, moduleName, platform)
        },
      },
      transformer: {},
    }
    const result = await withHozo(config)
    const context = {
      originModulePath: path.join(root, 'index.js'),
      resolveRequest(_context: unknown, moduleName: string) {
        if (moduleName === './App') return { type: 'sourceFile', filePath: app }
        throw new Error(`unresolved test module: ${moduleName}`)
      },
    }

    assert.equal(result.resolver.marker, 'preserved')
    assert.deepEqual(result.resolver.resolveRequest(context, './App', 'android'), {
      type: 'sourceFile',
      filePath: app,
    })
    result.resolver.resolveRequest(context, './App', 'ios')

    const state = JSON.parse(readFileSync(metroStatePath(root), 'utf8'))
    const androidBindings = state.stylexBindings.android
    const iosBindings = state.stylexBindings.ios
    assert.ok(
      androidBindings.some((entry: StylexResolvedBindings) =>
        entry.bindings.some(
          (binding: StylexResolvedBindings['bindings'][number]) =>
            binding.specifier === '@theme/styles' && binding.moduleId === androidStyles,
        ),
      ),
    )
    assert.ok(
      iosBindings.some((entry: StylexResolvedBindings) =>
        entry.bindings.some(
          (binding: StylexResolvedBindings['bindings'][number]) =>
            binding.specifier === '@theme/styles' && binding.moduleId === iosStyles,
        ),
      ),
    )

    const modules = new StylexModuleCache(path.join(root, CACHE_DIR, 'stylex-modules.json'))
    modules.replaceResolvedBindings(androidBindings)
    const compiler = createCompiler()
    compiler.setStylexModules(modules.moduleSources())
    const transformed = transformHozoSource(appSource, app, root, compiler, modules)
    assert.ok(transformed)
    assert.doesNotMatch(transformed, /stylex\.props/)
    assert.match(transformed, /marginTop:\s*37/)
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})

test('withHozo accepts a promised config and an explicit project root', async () => {
  const root = mkdtempSync(path.join(tmpdir(), 'hozo-metro-promise-'))
  try {
    mkdirSync(path.join(root, 'styles'))
    writeFileSync(path.join(root, 'styles', 'tailwind.css'), '@import "tailwindcss";\n')
    const result = await withHozo(Promise.resolve({ transformer: {} }), {
      root,
      css: 'styles/tailwind.css',
      content: { include: [] },
    })

    assert.match(result.transformer.babelTransformerPath, /index\.ts$/)
    assert.deepEqual(JSON.parse(readFileSync(metroStatePath(root), 'utf8')), {
      css: 'styles/tailwind.css',
      // Nothing was scanned, so nothing uses Tailwind, so no reset.
      preflight: false,
    })
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})

test('font faces are written once and imported only by Metro Web', async () => {
  const root = mkdtempSync(path.join(tmpdir(), 'hozo-metro-fonts-'))
  try {
    const css = '@font-face { font-family: "Fixture"; src: url("/Fixture.woff2"); }'
    await withHozo(
      { projectRoot: root, transformer: {} },
      { content: { include: [] }, fontFaceCss: css },
    )
    const state = JSON.parse(readFileSync(metroStatePath(root), 'utf8'))
    assert.equal(readFileSync(state.fontFaceCssPath, 'utf8'), `${css}\n`)

    const source = 'export const value = 1\n'
    const web = withWebFontFaces(source, path.join(root, 'App.tsx'), 'web', state.fontFaceCssPath)
    assert.match(web, /font-faces\.css/)
    assert.match(web, /export const value/)
    assert.equal(
      withWebFontFaces(source, path.join(root, 'App.tsx'), 'ios', state.fontFaceCssPath),
      source,
    )
    assert.equal(
      withWebFontFaces(source, path.join(root, 'App.tsx'), 'android', state.fontFaceCssPath),
      source,
    )
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})
