// Generated by scripts/generate-aria.mjs from aria-query. Do not edit.
//
// The ARIA specification, as a table: which roles exist, and what each one
// requires to mean anything. Derived rather than chosen -- the same move
// the Tailwind harness makes by asking Tailwind for its own class list,
// and for the same reason: a hand-kept copy of somebody else's
// specification drifts, and both halves go on looking reasonable while it
// does.
//
// Roles from the DPUB and Graphics modules are left out. They are separate
// specifications with their own host languages, and nothing in Hozo can
// say anything useful about them yet.

pub struct AriaRole {
    pub name: &'static str,
    /// Part of ARIA's ontology rather than something to write.
    ///
    /// The specification is explicit that authors must not use an abstract
    /// role. They are in the table because `role="widget"` deserves a
    /// better answer than "not a role": it is a real name, used wrongly.
    pub is_abstract: bool,
    /// States and properties the role is meaningless without.
    pub required_props: &'static [&'static str],
    /// Roles this one must be contained by.
    pub required_context: &'static [&'static str],
    /// Roles this one must contain.
    pub required_owned: &'static [&'static str],
    /// States and properties this role accepts *beyond* `GLOBAL_PROPS`.
    pub supported_props: &'static [&'static str],
    /// States and properties this role refuses, globals included.
    ///
    /// Small and load-bearing. Eleven roles prohibit an accessible name,
    /// and `generic` -- what a bare `<div>` or `<span>` is -- is one of
    /// them, as is `paragraph`. So an `accessibilityLabel` on a `View` or
    /// a `Paragraph` is a name assistive technology may ignore outright.
    pub prohibited_props: &'static [&'static str],
    /// Whether this role makes everything inside it presentational.
    ///
    /// `img` does, and that is the whole of it: an element carrying it
    /// is one graphic, and its descendants are not exposed. So a role that
    /// looks like an improvement -- a name where there was none -- takes
    /// away every control and every word inside the thing it named.
    pub children_presentational: bool,
}

/// The states and properties every role carries, from ARIA's base
/// `roletype`. Kept out of the rows, which each list only their own.
pub const GLOBAL_PROPS: &[&str] = &[
    "aria-atomic",
    "aria-busy",
    "aria-controls",
    "aria-current",
    "aria-describedby",
    "aria-details",
    "aria-dropeffect",
    "aria-flowto",
    "aria-grabbed",
    "aria-hidden",
    "aria-keyshortcuts",
    "aria-label",
    "aria-labelledby",
    "aria-live",
    "aria-owns",
    "aria-relevant",
    "aria-roledescription",
];

pub const ARIA_ROLES: &[AriaRole] = &[
    AriaRole { name: "alert", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "alertdialog", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-modal"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "application", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-activedescendant", "aria-disabled", "aria-errormessage", "aria-expanded", "aria-haspopup", "aria-invalid"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "article", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-posinset", "aria-setsize"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "banner", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "blockquote", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "button", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-disabled", "aria-expanded", "aria-haspopup", "aria-pressed"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "caption", is_abstract: false, required_props: &[], required_context: &["figure", "grid", "table"], required_owned: &[], supported_props: &[], prohibited_props: &["aria-label", "aria-labelledby"], children_presentational: false },
    AriaRole { name: "cell", is_abstract: false, required_props: &[], required_context: &["row"], required_owned: &[], supported_props: &["aria-colindex", "aria-colspan", "aria-rowindex", "aria-rowspan"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "checkbox", is_abstract: false, required_props: &["aria-checked"], required_context: &[], required_owned: &[], supported_props: &["aria-checked", "aria-disabled", "aria-errormessage", "aria-expanded", "aria-invalid", "aria-readonly", "aria-required"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "code", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &["aria-label", "aria-labelledby"], children_presentational: false },
    AriaRole { name: "columnheader", is_abstract: false, required_props: &[], required_context: &["row"], required_owned: &[], supported_props: &["aria-colindex", "aria-colspan", "aria-disabled", "aria-errormessage", "aria-expanded", "aria-haspopup", "aria-invalid", "aria-readonly", "aria-required", "aria-rowindex", "aria-rowspan", "aria-selected", "aria-sort"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "combobox", is_abstract: false, required_props: &["aria-controls", "aria-expanded"], required_context: &[], required_owned: &[], supported_props: &["aria-activedescendant", "aria-autocomplete", "aria-disabled", "aria-errormessage", "aria-expanded", "aria-haspopup", "aria-invalid", "aria-readonly", "aria-required"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "command", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "complementary", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "composite", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-activedescendant", "aria-disabled"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "contentinfo", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "definition", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "deletion", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &["aria-label", "aria-labelledby"], children_presentational: false },
    AriaRole { name: "dialog", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-modal"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "directory", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "document", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "emphasis", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &["aria-label", "aria-labelledby"], children_presentational: false },
    AriaRole { name: "feed", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["article"], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "figure", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "form", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "generic", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &["aria-label", "aria-labelledby"], children_presentational: false },
    AriaRole { name: "grid", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["row"], supported_props: &["aria-activedescendant", "aria-colcount", "aria-disabled", "aria-multiselectable", "aria-readonly", "aria-rowcount"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "gridcell", is_abstract: false, required_props: &[], required_context: &["row"], required_owned: &[], supported_props: &["aria-colindex", "aria-colspan", "aria-disabled", "aria-errormessage", "aria-expanded", "aria-haspopup", "aria-invalid", "aria-readonly", "aria-required", "aria-rowindex", "aria-rowspan", "aria-selected"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "group", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-activedescendant", "aria-disabled"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "heading", is_abstract: false, required_props: &["aria-level"], required_context: &[], required_owned: &[], supported_props: &["aria-level"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "img", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "input", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-disabled"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "insertion", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &["aria-label", "aria-labelledby"], children_presentational: false },
    AriaRole { name: "landmark", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "link", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-disabled", "aria-expanded", "aria-haspopup"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "list", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["listitem"], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "listbox", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["option"], supported_props: &["aria-activedescendant", "aria-disabled", "aria-errormessage", "aria-expanded", "aria-invalid", "aria-multiselectable", "aria-orientation", "aria-readonly", "aria-required"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "listitem", is_abstract: false, required_props: &[], required_context: &["directory", "list"], required_owned: &[], supported_props: &["aria-level", "aria-posinset", "aria-setsize"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "log", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "main", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "mark", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-braillelabel", "aria-brailleroledescription", "aria-description"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "marquee", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "math", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "menu", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["menuitem", "menuitemcheckbox", "menuitemradio"], supported_props: &["aria-activedescendant", "aria-disabled", "aria-orientation"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "menubar", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["menuitem", "menuitemcheckbox", "menuitemradio"], supported_props: &["aria-activedescendant", "aria-disabled", "aria-orientation"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "menuitem", is_abstract: false, required_props: &[], required_context: &["group", "menu", "menubar"], required_owned: &[], supported_props: &["aria-disabled", "aria-expanded", "aria-haspopup", "aria-posinset", "aria-setsize"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "menuitemcheckbox", is_abstract: false, required_props: &["aria-checked"], required_context: &["group", "menu", "menubar"], required_owned: &[], supported_props: &["aria-checked", "aria-disabled", "aria-errormessage", "aria-expanded", "aria-haspopup", "aria-invalid", "aria-posinset", "aria-readonly", "aria-required", "aria-setsize"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "menuitemradio", is_abstract: false, required_props: &["aria-checked"], required_context: &["group", "menu", "menubar"], required_owned: &[], supported_props: &["aria-checked", "aria-disabled", "aria-errormessage", "aria-expanded", "aria-haspopup", "aria-invalid", "aria-posinset", "aria-readonly", "aria-required", "aria-setsize"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "meter", is_abstract: false, required_props: &["aria-valuenow"], required_context: &[], required_owned: &[], supported_props: &["aria-valuemax", "aria-valuemin", "aria-valuenow", "aria-valuetext"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "navigation", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "none", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "note", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "option", is_abstract: false, required_props: &["aria-selected"], required_context: &[], required_owned: &[], supported_props: &["aria-checked", "aria-disabled", "aria-posinset", "aria-selected", "aria-setsize"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "paragraph", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &["aria-label", "aria-labelledby"], children_presentational: false },
    AriaRole { name: "presentation", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &["aria-label", "aria-labelledby"], children_presentational: false },
    AriaRole { name: "progressbar", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-valuemax", "aria-valuemin", "aria-valuenow", "aria-valuetext"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "radio", is_abstract: false, required_props: &["aria-checked"], required_context: &[], required_owned: &[], supported_props: &["aria-checked", "aria-disabled", "aria-posinset", "aria-setsize"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "radiogroup", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["radio"], supported_props: &["aria-activedescendant", "aria-disabled", "aria-errormessage", "aria-invalid", "aria-orientation", "aria-readonly", "aria-required"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "range", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-valuemax", "aria-valuemin", "aria-valuenow"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "region", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "roletype", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "row", is_abstract: false, required_props: &[], required_context: &["grid", "rowgroup", "table", "treegrid"], required_owned: &["cell", "columnheader", "gridcell", "rowheader"], supported_props: &["aria-activedescendant", "aria-colindex", "aria-disabled", "aria-expanded", "aria-level", "aria-posinset", "aria-rowindex", "aria-selected", "aria-setsize"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "rowgroup", is_abstract: false, required_props: &[], required_context: &["grid", "table", "treegrid"], required_owned: &["row"], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "rowheader", is_abstract: false, required_props: &[], required_context: &["row", "rowgroup"], required_owned: &[], supported_props: &["aria-colindex", "aria-colspan", "aria-disabled", "aria-errormessage", "aria-expanded", "aria-haspopup", "aria-invalid", "aria-readonly", "aria-required", "aria-rowindex", "aria-rowspan", "aria-selected", "aria-sort"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "scrollbar", is_abstract: false, required_props: &["aria-controls", "aria-valuenow"], required_context: &[], required_owned: &[], supported_props: &["aria-disabled", "aria-orientation", "aria-valuemax", "aria-valuemin", "aria-valuenow", "aria-valuetext"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "search", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "searchbox", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-activedescendant", "aria-autocomplete", "aria-disabled", "aria-errormessage", "aria-haspopup", "aria-invalid", "aria-multiline", "aria-placeholder", "aria-readonly", "aria-required"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "section", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "sectionhead", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "select", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-activedescendant", "aria-disabled", "aria-orientation"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "separator", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-disabled", "aria-orientation", "aria-valuemax", "aria-valuemin", "aria-valuenow", "aria-valuetext"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "slider", is_abstract: false, required_props: &["aria-valuenow"], required_context: &[], required_owned: &[], supported_props: &["aria-disabled", "aria-errormessage", "aria-haspopup", "aria-invalid", "aria-orientation", "aria-readonly", "aria-valuemax", "aria-valuemin", "aria-valuenow", "aria-valuetext"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "spinbutton", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-activedescendant", "aria-disabled", "aria-errormessage", "aria-invalid", "aria-readonly", "aria-required", "aria-valuemax", "aria-valuemin", "aria-valuenow", "aria-valuetext"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "status", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "strong", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &["aria-label", "aria-labelledby"], children_presentational: false },
    AriaRole { name: "structure", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "subscript", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &["aria-label", "aria-labelledby"], children_presentational: false },
    AriaRole { name: "superscript", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &["aria-label", "aria-labelledby"], children_presentational: false },
    AriaRole { name: "switch", is_abstract: false, required_props: &["aria-checked"], required_context: &[], required_owned: &[], supported_props: &["aria-checked", "aria-disabled", "aria-errormessage", "aria-expanded", "aria-invalid", "aria-readonly", "aria-required"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "tab", is_abstract: false, required_props: &[], required_context: &["tablist"], required_owned: &[], supported_props: &["aria-disabled", "aria-expanded", "aria-haspopup", "aria-posinset", "aria-selected", "aria-setsize"], prohibited_props: &[], children_presentational: true },
    AriaRole { name: "table", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["row"], supported_props: &["aria-colcount", "aria-rowcount"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "tablist", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["tab"], supported_props: &["aria-activedescendant", "aria-disabled", "aria-level", "aria-multiselectable", "aria-orientation"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "tabpanel", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "term", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "textbox", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-activedescendant", "aria-autocomplete", "aria-disabled", "aria-errormessage", "aria-haspopup", "aria-invalid", "aria-multiline", "aria-placeholder", "aria-readonly", "aria-required"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "time", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "timer", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "toolbar", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-activedescendant", "aria-disabled", "aria-orientation"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "tooltip", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "tree", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["treeitem"], supported_props: &["aria-activedescendant", "aria-disabled", "aria-errormessage", "aria-invalid", "aria-multiselectable", "aria-orientation", "aria-required"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "treegrid", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["row"], supported_props: &["aria-activedescendant", "aria-colcount", "aria-disabled", "aria-errormessage", "aria-invalid", "aria-multiselectable", "aria-orientation", "aria-readonly", "aria-required", "aria-rowcount"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "treeitem", is_abstract: false, required_props: &["aria-selected"], required_context: &["group", "tree"], required_owned: &[], supported_props: &["aria-checked", "aria-disabled", "aria-expanded", "aria-haspopup", "aria-level", "aria-posinset", "aria-selected", "aria-setsize"], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "widget", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &[], prohibited_props: &[], children_presentational: false },
    AriaRole { name: "window", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[], supported_props: &["aria-modal"], prohibited_props: &[], children_presentational: false },
];

/// Whether `name` is a role an author may write.
///
/// Abstract roles are excluded: they describe the ontology, and the
/// specification forbids writing them.
pub fn is_role(name: &str) -> bool {
    ARIA_ROLES.iter().any(|role| role.name == name && !role.is_abstract)
}

/// Whether `name` is one of ARIA's abstract roles.
pub fn is_abstract_role(name: &str) -> bool {
    ARIA_ROLES.iter().any(|role| role.name == name && role.is_abstract)
}

/// The specification's entry for `name`.
pub fn role(name: &str) -> Option<&'static AriaRole> {
    ARIA_ROLES.iter().find(|role| role.name == name)
}

/// Whether `role` accepts `prop` at all.
///
/// Prohibition wins over the globals: `aria-label` is global, and
/// `role="generic"` refuses it anyway.
pub fn allows_prop(role: &AriaRole, prop: &str) -> bool {
    !role.prohibited_props.contains(&prop)
        && (GLOBAL_PROPS.contains(&prop) || role.supported_props.contains(&prop))
}
