// Regenerates `crates/hozo_parser/src/aria.rs` from `aria-query`, which is
// the ARIA specification in machine-readable form -- the same package
// eslint-plugin-jsx-a11y and Testing Library read.
//
// Generated rather than written for the same reason the Tailwind
// conformance harness asks Tailwind for its own class list: a hand-kept
// copy of somebody else's specification is a copy that drifts, and the
// drift is invisible because both halves look reasonable. A test checks
// this file against the installed package.
//
//   node scripts/generate-aria.mjs

import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const { roles } = require('aria-query')

const entries = [...roles.entries()]
  .filter(([name]) => !name.startsWith('doc-') && !name.startsWith('graphics-'))
  .sort(([a], [b]) => a.localeCompare(b))

// The properties every role carries, which is what `roletype` -- ARIA's
// base role -- declares. Held once rather than repeated in every row: 1871
// entries become 273, for the same answers.
const globals = Object.keys(roles.get('roletype').props ?? {}).sort()

const rows = entries.map(([name, role]) => {
  const required = Object.keys(role.requiredProps ?? {}).sort()
  const context = (role.requiredContextRole ?? []).slice().sort()
  // `requiredOwnedElements` is a list of alternatives, each a path; the
  // first element of each path is the role that must be owned.
  const owned = [
    ...new Set((role.requiredOwnedElements ?? []).map((path) => path[0]).filter(Boolean)),
  ].sort()
  // What this role adds to the globals, and what it refuses outright.
  const supported = Object.keys(role.props ?? {})
    .filter((prop) => !globals.includes(prop))
    .sort()
  const prohibited = (role.prohibitedProps ?? []).slice().sort()
  const list = (xs) => `&[${xs.map((x) => JSON.stringify(x)).join(', ')}]`
  return `    AriaRole { name: ${JSON.stringify(name)}, is_abstract: ${role.abstract === true}, required_props: ${list(required)}, required_context: ${list(context)}, required_owned: ${list(owned)}, supported_props: ${list(supported)}, prohibited_props: ${list(prohibited)} },`
})

writeFileSync(
  'crates/hozo_parser/src/aria.rs',
  `// Generated by scripts/generate-aria.mjs from aria-query. Do not edit.
//
// The ARIA specification, as a table: which roles exist, and what each one
// requires to mean anything. Derived rather than chosen -- the same move
// the Tailwind harness makes by asking Tailwind for its own class list,
// and for the same reason: a hand-kept copy of somebody else's
// specification drifts, and both halves go on looking reasonable while it
// does.
//
// Roles from the DPUB and Graphics modules are left out. They are separate
// specifications with their own host languages, and nothing in Hozo can
// say anything useful about them yet.

pub struct AriaRole {
    pub name: &'static str,
    /// Part of ARIA's ontology rather than something to write.
    ///
    /// The specification is explicit that authors must not use an abstract
    /// role. They are in the table because \`role="widget"\` deserves a
    /// better answer than "not a role": it is a real name, used wrongly.
    pub is_abstract: bool,
    /// States and properties the role is meaningless without.
    pub required_props: &'static [&'static str],
    /// Roles this one must be contained by.
    pub required_context: &'static [&'static str],
    /// Roles this one must contain.
    pub required_owned: &'static [&'static str],
    /// States and properties this role accepts *beyond* \`GLOBAL_PROPS\`.
    pub supported_props: &'static [&'static str],
    /// States and properties this role refuses, globals included.
    ///
    /// Small and load-bearing. Eleven roles prohibit an accessible name,
    /// and \`generic\` -- what a bare \`<div>\` or \`<span>\` is -- is one of
    /// them, as is \`paragraph\`. So an \`accessibilityLabel\` on a \`View\` or
    /// a \`Paragraph\` is a name assistive technology may ignore outright.
    pub prohibited_props: &'static [&'static str],
}

/// The states and properties every role carries, from ARIA's base
/// \`roletype\`. Kept out of the rows, which each list only their own.
pub const GLOBAL_PROPS: &[&str] = &[
${globals.map((prop) => `    ${JSON.stringify(prop)},`).join('\n')}
];

pub const ARIA_ROLES: &[AriaRole] = &[
${rows.join('\n')}
];

/// Whether \`name\` is a role an author may write.
///
/// Abstract roles are excluded: they describe the ontology, and the
/// specification forbids writing them.
pub fn is_role(name: &str) -> bool {
    ARIA_ROLES.iter().any(|role| role.name == name && !role.is_abstract)
}

/// Whether \`name\` is one of ARIA's abstract roles.
pub fn is_abstract_role(name: &str) -> bool {
    ARIA_ROLES.iter().any(|role| role.name == name && role.is_abstract)
}

/// The specification's entry for \`name\`.
pub fn role(name: &str) -> Option<&'static AriaRole> {
    ARIA_ROLES.iter().find(|role| role.name == name)
}

/// Whether \`role\` accepts \`prop\` at all.
///
/// Prohibition wins over the globals: \`aria-label\` is global, and
/// \`role="generic"\` refuses it anyway.
pub fn allows_prop(role: &AriaRole, prop: &str) -> bool {
    !role.prohibited_props.contains(&prop)
        && (GLOBAL_PROPS.contains(&prop) || role.supported_props.contains(&prop))
}
`,
)
console.log(`wrote ${entries.length} ARIA roles`)
