// The generated-code ABI, derived from the modules that implement it.
//
// Compiled output imports Hozo's runtime pieces one leaf at a time --
// `import { HozoFlatList } from '@hozo/core/generated/flat-list'` -- and
// three things have to agree about what those leaves are: each owner's
// `exports` map, `@hozo/core`'s forwarding modules and their `exports`, and
// the compiler's table from an emitted name to the specifier that provides
// it. Written by hand, that is three lists, and this repository has already
// paid for keeping lists in step with each other (#417). So there is one
// source, the directory of leaf modules each owner keeps in
// `src/generated/`, and everything else is read off it.
//
// Why a leaf rather than a barrel: Metro does not tree-shake, so whatever
// module compiled output imports is what ships. Measured on
// `examples/native-demo`'s bench screen (#435), one barrel over the owners
// costs +33KB, one barrel per owner +18.6KB, and the pre-existing owner
// subpaths +0 -- only a module no coarser than what a screen uses can be
// smaller than that.
//
// Why through `@hozo/core`: compiled output lands in application source,
// and under strict pnpm an application can import only what it declared.
// It declared `@hozo/core`. Owners `@hozo/core` depends on are forwarded
// there; any other owner (`@hozo/rn-compat`) is an opt-in domain the
// application declares itself, and its leaves are addressed directly.
//
//   node scripts/generated-abi.mjs         # write
//   node scripts/generated-abi.mjs --check # verify, exit 1 on drift

import { existsSync, globSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const packagesRoot = path.join(root, 'packages')

/** The facade itself, whose `src/generated` is output rather than source. */
const FACADE = 'core'

const COMPILER_TABLE = path.join(packagesRoot, 'compiler', 'src', 'generated-abi.ts')

/**
 * Every leaf module, synchronously, from the file system alone.
 *
 * `native` is whether a `.native.ts` twin exists. A leaf without one is a
 * single implementation under every condition -- the Native-only layout
 * boundaries are that, because the Web backend never asks for them.
 */
export function generatedLeaves() {
  const leaves = []
  for (const file of globSync('*/src/generated/*.ts', { cwd: packagesRoot })) {
    const [owner, , , name] = file.replaceAll('\\', '/').split('/')
    if (owner === FACADE || name.includes('.native.') || name.includes('.test.')) continue
    const leaf = name.replace(/\.ts$/, '')
    const native = existsSync(
      path.join(packagesRoot, owner, 'src', 'generated', `${leaf}.native.ts`),
    )
    leaves.push({ owner, leaf, native })
  }
  leaves.sort((a, b) => a.leaf.localeCompare(b.leaf))

  const seen = new Map()
  for (const { owner, leaf } of leaves) {
    // A leaf name is the whole address once the owner is out of the path.
    if (seen.has(leaf)) {
      throw new Error(
        `generated leaf "${leaf}" exists in both @hozo/${seen.get(leaf)} and @hozo/${owner}`,
      )
    }
    seen.set(leaf, owner)
  }
  return leaves
}

/** The owners `@hozo/core` forwards: exactly the ones it depends on. */
export function facadedOwners() {
  const core = JSON.parse(readFileSync(path.join(packagesRoot, FACADE, 'package.json'), 'utf8'))
  return new Set(
    Object.keys(core.dependencies ?? {})
      .filter((name) => name.startsWith('@hozo/'))
      .map((name) => name.slice('@hozo/'.length)),
  )
}

/** Where compiled output imports a leaf from. */
export function leafSpecifier({ owner, leaf }, facaded = facadedOwners()) {
  return facaded.has(owner)
    ? `@hozo/${FACADE}/generated/${leaf}`
    : `@hozo/${owner}/generated/${leaf}`
}

/** Value exports of one module, as esbuild reads them -- types are erased. */
async function valueExports(file) {
  const { build } = await import('esbuild')
  const result = await build({
    entryPoints: [file],
    bundle: false,
    write: false,
    metafile: true,
    format: 'esm',
    outdir: path.join(root, '.generated-abi-probe'),
    logLevel: 'silent',
  })
  const [output] = Object.values(result.metafile.outputs)
  return [...output.exports].sort()
}

function facadeModule(owner, leaf) {
  return (
    `// Generated by scripts/generated-abi.mjs from packages/${owner}/src/generated/${leaf}.ts.\n` +
    `export * from '@hozo/${owner}/generated/${leaf}'\n`
  )
}

function compilerTable(entries) {
  const lines = entries.map(([name, specifier]) => `  ${name}: '${specifier}',`)
  return (
    '// Generated by scripts/generated-abi.mjs from packages/*/src/generated. Do not edit.\n' +
    '//\n' +
    '// Every name compiled output can import, and the specifier that provides it.\n' +
    '\n' +
    'export const GENERATED_ABI: Readonly<Record<string, string>> = {\n' +
    `${lines.join('\n')}\n` +
    '}\n'
  )
}

/** Every file this generator owns, with the content it should have. */
export async function expectedFiles() {
  const leaves = generatedLeaves()
  const facaded = facadedOwners()
  const files = new Map()
  const owners = new Map()

  for (const entry of leaves) {
    const dir = path.join(packagesRoot, entry.owner, 'src', 'generated')
    const names = await valueExports(path.join(dir, `${entry.leaf}.ts`))
    if (names.length === 0) {
      throw new Error(`@hozo/${entry.owner}/generated/${entry.leaf} exports no value`)
    }
    // The two halves of a leaf answer the same import. A name only one of
    // them has is an import that resolves on one platform and not the other.
    if (entry.native) {
      const native = await valueExports(path.join(dir, `${entry.leaf}.native.ts`))
      if (native.join() !== names.join()) {
        throw new Error(
          `@hozo/${entry.owner}/generated/${entry.leaf} exports [${names}] on the Web and [${native}] on Native`,
        )
      }
    }
    const specifier = leafSpecifier(entry, facaded)
    for (const name of names) {
      if (owners.has(name)) {
        throw new Error(`${name} is exported by both ${owners.get(name)} and ${specifier}`)
      }
      owners.set(name, specifier)
    }
    if (facaded.has(entry.owner)) {
      files.set(
        path.join(packagesRoot, FACADE, 'src', 'generated', `${entry.leaf}.ts`),
        facadeModule(entry.owner, entry.leaf),
      )
    }
  }

  const entries = [...owners].sort(([a], [b]) => a.localeCompare(b))
  files.set(COMPILER_TABLE, compilerTable(entries))
  return files
}

async function main() {
  const check = process.argv.includes('--check')
  const expected = await expectedFiles()
  const problems = []

  const facadeDir = path.join(packagesRoot, FACADE, 'src', 'generated')
  const stale = globSync('*.ts', { cwd: facadeDir })
    .map((name) => path.join(facadeDir, name))
    .filter((file) => !expected.has(file))

  for (const [file, content] of expected) {
    const current = existsSync(file) ? readFileSync(file, 'utf8') : undefined
    if (current === content) continue
    if (check) {
      problems.push(`${path.relative(root, file)} is out of date`)
    } else {
      mkdirSync(path.dirname(file), { recursive: true })
      writeFileSync(file, content)
    }
  }
  for (const file of stale) {
    if (check) problems.push(`${path.relative(root, file)} forwards a leaf that no longer exists`)
    else rmSync(file)
  }

  if (problems.length > 0) {
    console.error(`generated ABI drifted -- rerun node scripts/generated-abi.mjs:\n`)
    for (const problem of problems) console.error(`  - ${problem}`)
    process.exit(1)
  }
  const names = (await import('node:fs')).readFileSync(COMPILER_TABLE, 'utf8').match(/^ {2}\w+:/gm)
  console.log(
    `${check ? 'generated ABI is current' : 'wrote generated ABI'}: ${generatedLeaves().length} leaves, ${names?.length ?? 0} names`,
  )
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main()
}
