// One rule for compiled and fallback boxes. Rust includes the CSS directly;
// the published JS copy is generated, so an npm consumer needs no Rust files.
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../', import.meta.url))
const destination = path.join(root, 'packages/engine/src/view-base-css.ts')

export function generateViewBase(check = false) {
  const css = readFileSync(path.join(root, 'crates/hozo_web/src/view-base.css'), 'utf8').replaceAll(
    '\r\n',
    '\n',
  )
  const literal = css.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('${', '\\${')
  const text = `// Generated by scripts/view-base.mjs from the Web backend's shared CSS.\nexport const HOZO_VIEW_BASE_CSS = \`${literal}\`\n`
  if (check) {
    if (readFileSync(destination, 'utf8').replaceAll('\r\n', '\n') !== text) {
      throw new Error(
        'View base CSS differs between compiler and fallback; run node scripts/view-base.mjs',
      )
    }
  } else writeFileSync(destination, text)
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generateViewBase(process.argv.includes('--check'))
}
